s = """


<html>
<head>
<title>Frazier Lab - Internal Website</title>
<link rel="stylesheet" href="/SWHLabPHP/src/browse/style.css">

    <script>
    function copyToClipboard(elementId) {
      // Create a "hidden" input
      var aux = document.createElement("input");
      // Assign it the value of the specified element
      aux.setAttribute("value", document.getElementById(elementId).innerHTML);
      // Append it to the body
      document.body.appendChild(aux);
      // Highlight its content
      aux.select();
      // Copy the highlighted text
      document.execCommand("copy");
      // Remove it from the body
      document.body.removeChild(aux);
    }
    </script>
    <style>
/* TODO: MOVE MATURE STYLES TO CSS FILE */
li {line-height: 150%;}
.section{
    width: 85%;
    padding-left: 20px;
    padding-top: 2px;
    padding-bottom: 10px;
    padding-right: 4px;
    background-color: white;
    border: 1px solid #25658a;
    border-left: 10px solid #25658a;
    box-shadow: 5px 5px 10px  rgba(0, 0, 0, 0.15); 
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 50px;
}

.sectionMenu{
    font-size: 120%;
    width: 85%;
    padding-left: 20px;
    padding-right: 4px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 10px;
}

.menuSep{
    color: #CCC;
}

iframe{
    display: block;
    width: 100%; 
    border: none;
}


.bannerBottom{
	background-image: url(/SWHLabPHP/src/browse/images/banner_die_blue.png);
    background-size: contain;
    background-repeat: no-repeat;

	padding-top: 20px;
	padding-bottom: 20px;
    background-position: left bottom;
    margin: -8px;
    margin-bottom: 20px;

}
</style>

<script>
function updatePath(){
    var url = document.getElementById("pathForUrlConv").value;

    while (url.indexOf("\\")>=0){
        url = url.replace("\\", "/");
    }
    
    document.getElementById('urlFromPath').href = "invalid path";
    document.getElementById('urlFromPath').innerHTML = "invalid path";

    url = url.replace("x:", "X:");

    if (url.indexOf('X:') == -1) {
        return;
    }
    url = url.replace("X:/", "/X/");
    url = 'http://192.168.1.9'+url;
    document.getElementById('urlFromPath').href = url;
    document.getElementById('urlFromPath').innerHTML = url;
}

// the function is called only on keypresses. This captures mouse pastes.
setInterval(updatePath, 100);

</script>
</head>
<body>
<div class='banner'>
    <div style="font-size: 250%; font-weight: bold; padding-left: 20px; position: relative; top: -15px;">
        Frazier Laboratory
    </div>
    <div style="font-size: 80%; font-style: italic; padding-left: 20px; position: relative; top: -22px;">
        <!--Page generated by 192.168.1.9 on 2019-07-12 12:56:36-->
        Internal Laboratory Website
        <br>&nbsp;
    </div>
</div>

<br><br><br>

<div class="sectionMenu">
    Links:
    <!--
    <a class='menuLink' href='#experiments'>Experiments</a>, 
    <a class='menuLink' href='#animal'>Animals</a>, 
    <a class='menuLink' href='#surgical'>Surgeries</a>, 
    -->
    <a class='menuLink' href='https://cjflab.org/'>CJFLab.org</a>,
    <a class='menuLink' href='onenote:https://uflorida.sharepoint.com/sites/FrazierLab/SiteAssets/Frazier%20Lab%20Main%20Notebook/'>OneNote</a>,
    <a class='menuLink' href='https://uflorida.sharepoint.com/sites/FrazierLab/Shared%20Documents/' style='background-color: #e8f28e;'>&nbsp;SharePoint&nbsp;</a>,
    <a class='menuLink' href='http://192.168.1.9/X/Software/OriginC/On-line/git/CJFLab/documentation/php/'>Origin Commands</a>
</div>

<div class="sectionMenu">
    Technical:
    <a class='menuLink' href='#browseABF'>ABF Browser</a>, 
    <a class='menuLink' href='#fileLocator'>ABF Locator</a>,
    <a class='menuLink' href='#browseFolder'>Path-to-URL</a>, 
    <a class='menuLink' href='broken.html'>broken URL detector</a>
</div>

<br><br>

<div class="section"><a name='experiments'></a><h1>All Experiments</h1>
<h2>PVN GCaMP Experiments</h2>
<ul>
<li>Using GCaMP to create OXT sniffers: <a href="http://192.168.1.9/SWHLabPHP/recode/src?view=abf&amp;fldr=X:\Data\OT-Cre\OT-GCaMP-nonspecific&amp;frames">data</a>, <a href="http://192.168.1.9/X/Data/OT-Cre/OT-GCaMP-nonspecific/OT-GCaMP-nonspecific-notebook.pdf">notebook</a></li>
</ul>
<h2>AT1-Cre Experiments</h2>
<ul>
<li>AT1-Cre (ChR2 injected in SFO) finding BLS in VP+ PVN MCNs:
<a href="http://192.168.1.9/SWHLabPHP/recode/src?view=abf&amp;fldr=X:\Data\AT1-Cre\SFO%20Chr2%20PVN\abfs&amp;frames">data</a> </li>
<li>AT1-Cre (ChR2 injected in MPO) finding BLS in VP+ PVN MCNs:
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\AT1-Cre\MPO%20Chr2%20PVN\abfs&amp;frames">data</a>,
<a href="http://192.168.1.9/X/Data/AT1-Cre/summary_mpo.pdf">notebook</a></li>
<li>AT1-Cre (ChR2 studies in NTS):
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\AT1-Cre\global%20Chr2%20NTS\data&amp;frames">data</a> (global),
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\AT1-Cre\nodose%20Chr2%20injection%20NTS\data&amp;frames">data</a> (nodose injection),
<a href="/X/Data/AT1-Cre/summary_nts.pdf">notebook</a> (global and nodose) </li>
<li>AT1-Cre (GCaMP6f injected in MPO/OVLT):
<a href="http://192.168.1.9/X/Data/AT1-Cre/MPO%20GCaMP6f/data/">data</a>,
<a href="http://192.168.1.9/X/Data/AT1-Cre/summary_mpo_gcamp.pdf">notebook</a></li>
<li>AT1-Cre (ChR2 and halo injected in MPO):
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\AT1-Cre\MPO%20Chr2%20PVN\abfs&amp;frames">data</a>,
<a href="/X/Data/AT1-Cre/summary_mpo.pdf">notebook</a>   </li>
</ul>
<h2>OTR-Cre Experiments</h2>
<ul>
<li>OTR-Cre (ChR2 injected in PFC):
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\OTR-Cre\PFC%20inj%20CHR2%20BLA%20phenotype\abfs&amp;frames">BLA data</a>,
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\OTR-Cre\PFC%20inj%20CHR2%20PFC%20IPSCs\abfs&amp;frames">PFC IPSC data</a>,
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\OTR-Cre\PFC%20inj%20CHR2%20PFC%20EPSCs\abfs&amp;frames">PFC EPSC data</a>,
<a href="http://192.168.1.9/X/Data/OTR-Cre/PFC%20inj%20CHR2%20BLA%20phenotype/summary-otr-pfc-chr2-bla.pdf">notebook</a> </li>
<li>OTR-Cre (GCaMP6f injected in PFC - patch and linescan): <a href="http://192.168.1.9/X/Data/OTR-Cre/GCaMP6f%20PFC%20injection%20patch%20and%20linescan/symmary-gcamp-patch.pdf">notebook</a>, <a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\OTR-Cre\GCaMP6f%20PFC%20injection%20patch%20and%20linescan\2019-02-13\abfs&amp;frames">abfs</a></li>
<li>OTR-Cre (GCaMP6f injected in PFC - Yalun's manuscript):
<a href="http://192.168.1.9/X/Data/OTR-Cre/GCaMP6f%20PFC%20injection%20field%20imaging-round%202/">videos</a>,
<a href="http://192.168.1.9/X/Data/OTR-Cre/GCaMP6f%20PFC%20injection%20field%20imaging-round%202/figure/figure.png">figure</a>,
<a href="http://192.168.1.9/X/Data/OTR-Cre/GCaMP6f%20PFC%20injection%20field%20imaging-round%202/figure/figure2.png">figure2</a></li>
<li>OTR-Cre (GCaMP6f injected in PFC - testing fiber photometry): <a href="https://www.youtube.com/watch?v=r5iyD7B55EE">link</a> video puffing glutamate  </li>
<li>OTR-Cre (eYFP injected in PFC) response to OXT:
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\OTR-Cre\PFC%20inj%20eYFP%20OXT%20response\abfs&amp;frames">data</a>,
<a href="http://192.168.1.9/dataX/OTR-Cre/PFC%20inj%20eYFP%20OXT%20response/pics2.html">cell pics</a>,
<a href="http://192.168.1.9/dataX/OTR-Cre/PFC%20inj%20eYFP%20OXT%20response/summary.pdf">notebook</a></li>
<li>OTR-Cre (ChR2 injected in BNST) local synapses, synapses in lateral septum and hippocampus:
<a href="/X/Data%20Analysis/OTR-Cre%20BNST%20injection%20optogenetics/paper%20outline.pdf">notebook</a></li>
<li>OTR-Cre (ChR2 injected in VTA) intrinsic and synaptic properties:
<a href="/X/Data%20Analysis/OTR-Cre%20VTA%20optogenetics/results.pdf">notebook</a> </li>
</ul>
<h2>Aging Experiments</h2>
<ul>
<li>Aging BLA round 1 (March 2017) seeks to replicate Kyle's GABA tone data:
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\F344\Aging%20BLA\basal%20excitability%20round1\abfs&amp;frames">data</a>,
<a href="http://192.168.1.9/X/Data/F344/Aging%20BLA/basal%20excitability%20round1/onenote_summary.pdf">notes</a>,
<a href="http://192.168.1.9/X/Data/F344/Aging%20BLA/basal%20excitability%20round1/summary%20aging%20round%201.pdf">notebook</a>     </li>
<li>Aging BLA round 2 (Oct 2017) studies intrinsics and tone in all BLA neurons:
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\F344\Aging%20BLA\basal%20excitability%20round2\abfs&amp;frames">data</a>,
<a href="http://192.168.1.9/files/blagrant-2017-12-18.pdf">grant fig</a>,
<a href="http://192.168.1.9/files/blagrant-2017-12-18-alt.png">alt color</a>,
<a href="/X/Data/F344/Aging%20BLA/basal%20excitability%20round2/summary%20round%202.pdf">notebook</a></li>
<li>Aging BLA round 3 (June 2018) studies retrogradely-labeled BLA neurons (from PFC and NAc):
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\F344\Aging%20BLA\basal%20excitability%20round3&amp;frames">data</a>,
<a href="http://192.168.1.9/X/Data/F344/Aging%20BLA/basal%20excitability%20round3/summary.pdf">notebook</a>,
<a href="http://192.168.1.9/X/Data/F344/Aging%20BLA/printable-map.pdf">map</a>,
<a href="https://uflorida.sharepoint.com/sites/FrazierLab/BLAaging/SitePages/Home.aspx">SharePoint</a></li>
<li>Aging BLA halorhodopsin experiments (Caesar):
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\F344\Aging%20BLA\halo\data&amp;frames">data</a>,
<a href="http://192.168.1.9/dataX/F344/Aging%20BLA/halo/summary.pdf">notebook</a>,
<a href="http://www.jneurosci.org/content/jneuro/37/48/11537.full.pdf">publication</a></li>
<li>Aging Hippocampus (hilus) Interneuron AMPA/NMDA Ratio: <a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\F344\Aging%20Hipp\AMPA-NMDA-Ratio&amp;frames">data</a></li>
<li>Aging Hippocampus (CA3) Pyramidal E/I Balance: <a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\F344\Aging%20Hipp\E-I-balance&amp;frames">data</a></li>
<li>Aging LC halorhodopsin experiments (Bizon)
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\TH-Cre%20(rat)&amp;frames">data</a></li>
</ul>
<h2>OT-Cre Experiments</h2>
<ul>
<li>OT-Cre osmolality on MCNs (Wanhui):
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\OT-Cre\calcium-mannitol&amp;frames">data</a>,
<a href="http://192.168.1.9/X/Data%20Analysis/_Core%20Projects/OXT%20PVN%20mannitol/summary.pdf">notebook</a>,
<a href="https://uflorida.sharepoint.com/sites/FrazierLab/OTMCNs/SitePages/Home.aspx">SharePoint</a></li>
<li>OT-Cre OT signaling on BNST-CeA neurons (Wanhui):
<a href="http://192.168.1.9/SWHLabPHP/recode/src?view=abf&amp;fldr=X:/Data/OT-Cre/BNST-CeA%20pathway&amp;frames">data</a>,
<a href="http://192.168.1.9/X/Data%20Analysis/OXT%20on%20BNST-CeA/summary.pdf">notebook</a>,</li>
<li>OT-Cre GCaMP6f injected in PVN: <a href="http://192.168.1.9/X/Data/OT-Cre/OT-GCaMP%20injection%20PVN/">data</a></li>
<li>OT-Cre GCaMP6f intrinsic / bred in: <a href="http://192.168.1.9/X/Data/OT-Cre/OT-GCaMP%20intrinsic/summary-ot-cre-gcamp-intrinsic.pdf">notebook</a></li>
</ul>
<h2>Piriform Cortex Project</h2>
<ul>
<li>PIR project <a href="http://192.168.1.9/X/Data%20Analysis/PIR%20Oxytocin/summary-PIR-OXT.pdf">summary of findings</a></li>
<li>PIR cortex <a href="http://192.168.1.9/X/Data%20Analysis/PIR%20Oxytocin/PIR%20crash%20course/Oxytocin%20Signaling%20in%20the%20Piriform%20Cortex.pdf">crash course</a></li>
<li>PIR manuscript <a href="http://192.168.1.9/dataX/SD/Piriform%20Oxytocin/00%20pilot%20experiments/2016-10-24%20all%20early%20experiments/manuscript%20development/backup.pdf">draft</a> from Jan 2017</li>
<li>PIR experiments
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\SD\Piriform%20Oxytocin&amp;frames">data</a>,
<a href="http://192.168.1.9/X/Data%20Analysis/PIR%20Oxytocin/2018%20PIR%20project%20revisited/nov-dec-2018-TS-WS-SH.pdf">notebook</a></li>
<li>Hippocampal Mossy cell <a href="http://192.168.1.9/X/Users_Public/Scott/dissertation/2016-04-07%20final%20dissertation/Scott%20Harden%20dissertation.pdf">idea</a> - Figure 4-8 is just like PIR. Figures 4-10 through 4-12 are meaningful.</li>
</ul>
<h2>CRH PVN Experiments (isotonic vs hypertonic)</h2>
<ul>
<li>Jan 2017 - Astrocyte calcium imaging in CRH-tdTom mice:
<a href="http://192.168.1.9/X/Data/C57/PVN%20astrocyte%20calcium%20imaging/2p/">data</a>,
<a href="http://192.168.1.9/X/Data%20Analysis/_Tech%20Development/C57%20PVN%20astrocyte%20calcium%20imaging/onenote_summary.pdf">notebook</a>, <a href="https://youtu.be/rb61dyACFYw">Fluo-4 AM video</a></li>
<li>Jul 2017 - SH re-investigated CRH+ PVN neurons in isotonic vs hypertonic mice: <a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\CRH-Cre\oxt-tone\injection-gain-analysis-2&amp;frames">data</a>, <a href="http://192.168.1.9/X/Data/CRH-Cre/oxt-tone/injection-gain-analysis-1/analysis/outAP_all/index.html">intrinsic data mining</a>, <a href="http://192.168.1.9/X/Data/CRH-Cre/oxt-tone/crh-project-revisited-2017-2018.pdf">notebook</a>. This study investigated many things, including:
<ul>
<li>compared intrinsic properties between isotonic/hypertonic groups</li>
<li>documented methods for mouse saline injection (according to Helmut)</li>
<li>publication-ready representative images (standard and 2P) of CRH reporter</li>
<li>determined GABA-A is excitatory at -70 mV with Dipa's internal</li>
<li>applied glycine (to determine if it is excitatory at -70 mV)</li>
<li>applied L-368 to ramps to identify reversal potential (but found no effect)</li>
<li>tried applying 600 nM OXT (not TGOT) to CRH cells (no effect)</li>
<li>tried high dose OXT (5 mM) on AP ramps and sustained firing (no effects)</li>
</ul></li>
<li>Nov 2017 - SH applied OXT (not TGOT) to CRH+ PVN neurons: <a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\CRH-Cre\oxt-tone\OXT-on-CRH-neurons&amp;frames">data</a></li>
<li>Aug 2018 - WS applied OXT (not TGOT) to CRH+ BNST neurons (it had no effect): <a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\CRH-Cre\2018-08-17%20OT%20in%20BNST\2018-08-17%20characterization&amp;frames">data</a></li>
<li>Oct 2018 (and June 2019) - WS pre-incubated neurons in OXT: <a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\CRH-Cre\oxt-tone\OXT-preincubation&amp;frames">data</a></li>
<li>Feb 2019 - Effects of micro-doses of TGOT on CRH+ PVN neurons: <a href="https://uflorida.sharepoint.com/sites/FrazierLab/Shared%20Documents/Manuscripts/Pati%20et%20al%20-%20CRH%20PVN%20OT%20Tone/data%20anaysis/CRH%20microdose/2019-02-20%20TGOT%20microdose%20on%20CRH%20neurons.pdf">notebook</a>, <a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;frames=&amp;fldr=X%3A%5CData%5CCRH-Cre%5Coxt-tone%5CTGOT+microdose+on+PVN+neurons">data</a></li>
<li>Apr 2019 - Salt-loading 50nM TGOT on CRH+ PVN neurons: <a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\CRH-Cre\oxt-tone\Salt%20loading%20TGOT%2050nm&amp;frames">data</a></li>
<li>June 2019 - Picospritzing TGOT on CRH+ PVN neurons: <a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\CRH-Cre\oxt-tone\puffed%20TGOT\abfs&amp;frames">data</a>, <a href="http://192.168.1.9/X/Data/CRH-Cre/oxt-tone/puffed%20TGOT/summary-crh-tom-puffed-tgot.pdf">notebook</a></li>
<li>June 2019 (and Oct 2018) - WS pre-incubated neurons in OXT: <a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\CRH-Cre\oxt-tone\OXT-preincubation&amp;frames">data</a></li>
</ul>
<h2>Additional Experiments</h2>
<ul>
<li>Rat NTS Fluo-4 Imaging (stimulator and CART): <a href="http://192.168.1.9/X/Data/SD/NTS%20GCaMP%20CART/notebook-nts-gcamp-cart.pdf">notebook</a>, <a href="http://192.168.1.9/X/Data/SD/NTS%20GCaMP%20CART">data</a></li>
<li>AngII PFC project (Amy):
<a href="http://192.168.1.9/X/Users_Public/Amy/project.pdf">notebook</a>,
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\AT1-Cre\amy%20rotation%20project&amp;frames">AT1-Cre data</a>,
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\SD\amy%20angiotensin%20project\data&amp;frames">rat pup data</a>,
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\AT1-Cre\MPO%20Chr2%20PVN\abfs&amp;frames">MPO data</a>,
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\AT1-Cre\MPO%20Chr2%20PVN\abfs\VP%20on%20PVN-RVLM%20neurons&amp;frames">MPO/RVLM data</a>,
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\C57\OVLT%20angiotensin&amp;frames">C57 Ang-II OVLT</a></li>
<li>Tat Project (Thomas):
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\C57\Tat%20project&amp;frames">data</a>,
<a href="http://192.168.1.9/dataX/C57/Tat%20project/summary-tat.pdf">notebook</a></li>
<li>V1A receptor antagonist experiments (SS): <a href="http://192.168.1.9/X/Data%20Analysis/_Individual%20Workspaces/Sarthak/AVP_Lateral%20Septum/results.jpg">results</a></li>
<li>D2R-Cre Rat Halo Experiment:
<a href="http://192.168.1.9/X/Data%20Analysis/D2R%20rat%20halo/summary_rat_d2r_halo.pdf">notebook</a>,
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\winstar\D2R%20NAc%20halo\abfs&amp;frames">data</a></li>
<li>OXT response in BLA-projecting PFC neurons: <a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\C57\BLA%20injection%20microspheres\technique%20development\abfs&amp;frames">data</a>, <a href="http://192.168.1.9/X/Data%20Analysis/C57%20OXT%20response%20in%20BLA-projecting%20PFC%20neurons/manuscript-figure-7.png">manuscript figure</a>, <a href="http://192.168.1.9/SWHLabPHP/src/browse/surgeries2.php">surgery records</a>, (notebook and origin project are in Yalun's sharepoint, NOT ON THE X-DRIVE!)</li>
<li>Early retrograde microsphere experiments:
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\C57\BLA%20injection%20microspheres\technique%20development\abfs&amp;frames">C57 BLA inj</a>,
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\C57\PFC%20injection%20microspheres\technique%20development\abfs&amp;frames">C57 PFC inj</a>,
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\OT-Cre\microsphere%20testing\PFC%20injection&amp;frames">OT-Tom PFC inj</a></li>
<li>DREADD experiments:
<a href="/SWHLabPHP/src/browse/surgeries2.php">surgeries</a>,
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;fldr=X:\Data\C57\dreadd%20experiments&amp;frames">data</a>,
<a href="http://192.168.1.9/X/Users_Public/Jeff/2018_04_02_0013.png">final figure</a>,
<a href="http://192.168.1.9/dataX/C57/dreadd%20experiments/summary.pdf">notebook</a></li>
<li>Protocol: <a href="http://192.168.1.9/X/Users_Public/Scott/protocols/histology%20and%20IHC/injection%20slide%20processing.pdf">Slice processing for microsphere-injected animals</a></li>
<li>OT signaling in the LHA (response to TGOT and OT-Cre/ChR2 BLS):
<a href="http://192.168.1.9/SWHLabPHP/recode/src/?view=abf&amp;frames&amp;fldr=X:\Data\OT-Cre\OT-ChR2%20characterization\abfs">data</a>,
<a href="http://192.168.1.9/X/Data%20Analysis/zFolders/LHA%20OXT%20signaling/notes/onenote_notes3.pdf">notebook</a></li>
<li>Troubleshooting GCaMP6f field imaging in OT-Cre and GABA-Cre (PFC injection):
<a href="http://192.168.1.9/X/Data%20Analysis/GCaMP6f%20PFC%20OXT%20response/onenote_notes.pdf">notes</a>,
<a href="http://192.168.1.9/X/Data%20Analysis/GCaMP6f%20PFC%20OXT%20response/summary%202017-06-11.pdf">notebook</a> </li>
<li>Evoked GLU release in the NAc for Peris Grant:
<a href="http://192.168.1.9/X/Data%20Analysis/_Single%20Shot/NAC%20glutamate%20signaling%20Peris%20(R21)/onenote_summary.pdf">notes</a>,
<a href="http://192.168.1.9/X/Data%20Analysis/_Single%20Shot/NAC%20glutamate%20signaling%20Peris%20(R21)/summary.png">ephys figure</a>, and
<a href="http://192.168.1.9/X/Data%20Analysis/_Single%20Shot/NAC%20glutamate%20signaling%20Peris%20(R21)/notes/diagram.png">diagram</a> </li>
<li>TGOT induces sIPSCs in mouse BNST: <a href="http://192.168.1.9/X/Data%20Analysis/C57%20TGOT%20effects%20in%20BNST%20and%20CeA/summary.pdf">notebook</a> (first demonstrated action of TGOT in our lab)</li>
<li>Two-photon calcium imaging in OT+ MCNs (OTA vs TGOT) <a href="http://192.168.1.9/X/Data%20Analysis/_Single%20Shot/PVN%20magno%20OXT%202P%20(for%20MH%20R01)/2P%20MCN%20TGOT%202014-08-11.pdf">R01 grant figure and follow-up </a> and <a href="http://192.168.1.9/X/Data%20Analysis/_Single%20Shot/PVN%20magno%20OXT%202P%20(for%20MH%20R01)/OT%20IHC%20filled%20neuron/fig1.png">IHC of OXT/NP1 in rat PVN</a></li>
<li>For information on projects before 2017, figure out who did the experiments and read their lab notebook</li>
</ul><div align='right' style='font-size: 80%; color: #CCC; padding-right: 10px;'><a href='edit/?mdFileName=experiments.md'>EDIT THIS PAGE</a></div></div>
<div class="section"><a name='surgical'></a><h1>Surgical Resources</h1>
<ul>
<li>Frazier lab <a href="http://192.168.1.9/SWHLabPHP/src/browse/surgeries2.php">surgery records, coordinates, and injection photos</a></li>
<li>Allen Brain Atlas <a href="http://mouse.brain-map.org/experiment/thumbnails/100142143">slices with coordinates</a> and <a href="http://help.brain-map.org/download/attachments/2818171/InjectionSites_and_StereotaxicCoordinates.pdf">coordinate PDF</a></li>
</ul><div align='right' style='font-size: 80%; color: #CCC; padding-right: 10px;'><a href='edit/?mdFileName=surgical.md'>EDIT THIS PAGE</a></div></div>
<div class="section"><a name='animal'></a><h1>Animal Characterization</h1>
<ul>
<li><a href="http://192.168.1.9/X/Users_Public/Scott/protocols/misc/transgenic-animals/transgenic-animals.pdf">Transgenic Animal Cheat Sheet</a> (PDF)</li>
<li>All mouse line <a href="http://192.168.1.9/X/Users_Public/Scott/protocols/misc/transgenic-animals/transgenic-mouse-lines.xlsx">notes</a> (XLS)</li>
</ul>
<p><strong>OT-Cre/Tom Mouse Line</strong> - <em>This mouse line expresses tdTomato in OT-Cre neurons</em></p>
<ul>
<li>brain map:
<a href="http://192.168.1.9/X/Data/OT-Cre/brain-map/male/">male</a>,
<a href="http://192.168.1.9/X/Data/OT-Cre/brain-map/female/images/">female</a> (coronal and horizontal sections)</li>
<li>Immuno-amplified tdTomato in the PFC:
<a href="http://192.168.1.9/X/Data/OT-Cre/brain-map/2017-11-09%20PFC/map.jpg">488</a>,
<a href="http://192.168.1.9/X/Data/OT-Cre/brain-map/2017-12-06%20PFC/best-pics/map.jpg">594 (better)</a></li>
<li>PVN tdTom/OT IHC:
<a href="http://192.168.1.9/X/Data/OT-Cre/calcium-mannitol/fishing/2017-06-16%20mannitol%20linescans/data/linescans/2p/ZSeries-06302017-1049-699/MIP/out_merge.png">merged</a>,
<a href="http://192.168.1.9/X/Data/OT-Cre/calcium-mannitol/fishing/2017-06-16%20mannitol%20linescans/data/linescans/2p/ZSeries-06302017-1049-699/MIP/animated.gif">aniGray</a>,
<a href="http://192.168.1.9/X/Data/OT-Cre/calcium-mannitol/fishing/2017-06-16%20mannitol%20linescans/data/linescans/2p/ZSeries-06302017-1049-699/MIP/animated2.gif">aniCol</a></li>
<li>IHC <a href="http://192.168.1.9/X/Data/OT-Cre/brain-map/onenote_summary.pdf">notes</a> regarding antibodies and off-target Cre expression</li>
</ul>
<p><strong>OT-Cre/ChR2 Mouse Line</strong> - <em>This mouse line expresses ChR2 in OT-Cre neurons. Although the rate of false-positive Cre/ChR2 expression may be 1 in 10,000, it is enough to label several non-OT neurons per slice. This means light-evoked currents (i.e., glutamate) may originate from non-OT neurons. This line is no longer being actively bred.</em></p>
<ul>
<li><a href="/X/Data/OT-Cre/OT-ChR2%20brain%20map/OT-001/pvn-son-lowqual.png">PVN/SON slice</a>   (20 micron slice from Yalun)</li>
<li><a href="/X/Data/OT-Cre/OT-ChR2%20brain%20map/OT-001/PIR-montage/pir_montage.png">PIR slice</a>   (20 micron slice from Yalun)</li>
</ul>
<p><strong>CRH-Cre/Tom Mouse Line</strong> - <em>This mouse line expresses tdTomato in OT-Cre neurons</em></p>
<ul>
<li>brain map (male):
<a href="http://192.168.1.9/X/Data/CRH-Cre/brain-map/montage%2017801%20v2/enhanced_tdTom.png">Tom</a>  ,
<a href="http://192.168.1.9/X/Data/CRH-Cre/brain-map/montage%2017801%20v2/enhanced_best.png">Tom+NP1</a> </li>
<li>PVN tdTom/OT IHC:
<a href="http://192.168.1.9/X/Data/CRH-Cre/brain-map/2p%20pvn%20flat/enhanced.png">Tom+NP1</a></li>
</ul>
<p><strong>SD Rat Pup Neuroanatomy</strong></p>
<ul>
<li>Rat pup (p16), horizontally sectioned, slice containing BLA:
<a href="http://192.168.1.9/X/Users_Public/Todd/Lab/practice/2017-07-19%20TS%20practice/imaging/montage_enhanced.jpg">original</a>   and
<a href="http://192.168.1.9/X/Users_Public/Todd/Lab/practice/2017-07-19%20TS%20practice/imaging/annotated.png">annotated</a></li>
</ul><div align='right' style='font-size: 80%; color: #CCC; padding-right: 10px;'><a href='edit/?mdFileName=animal.md'>EDIT THIS PAGE</a></div></div>
<div class="section"><a name='misc'></a><h1>Miscellaneous</h1>
<ul>
<li>Color selection tool for scientific data graphs: <a href="http://tools.medialab.sciences-po.fr/iwanthue/">I want hue</a></li>
<li>Choosing colormaps for scientific data representation (<a href="https://www.youtube.com/watch?v=xAoljeRJ3lU&amp;feature=youtu.be">video</a>)</li>
<li><a href="http://192.168.1.9/X/Users_Public/Scott/protocols/misc/transgenic-animals/transgenic-animals.pdf">Transgenic Animal Cheat Sheet</a></li>
<li>Frazier lab <a href="/files/illustrations/filter_cubes/index.html">filter cube charts</a></li>
<li>Scott's <a href="http://192.168.1.9/X/Users_Public/Scott/illustrations/2018-09-17%20tissue%20processing/frazlab-tissue-processing.pdf">Tissue Processing Guide</a> (describes how to save/process injection sites)</li>
<li><a href="https://resources.rndsystems.com/images/site/rnd-systems-ihc-protocol-br.pdf">R&amp;D Systems IHC Protocol Guide</a></li>
<li><a href="https://github.com/swharden/two-photon/tree/master/documentation/startup-and-shutdown">2P startup and shutdown notes</a></li>
<li><a href="https://github.com/swharden/two-photon/tree/master/software/time-series-analysis/2016-12-02-excel">2P time series (video) analysis with Excel</a> (for GCaMP or Fluo-4 AM experiments)</li>
<li><a href="files/2p-shutter.pdf">two photon shutter build</a></li>
<li><a href="https://youtu.be/VrKIg0IQL98">old 2P laser calibration video</a> (see note about <a href="https://youtu.be/Bt9zSfinwFA">VVS</a>)</li>
<li>Calcium imaging using Fluo4 is possible in tdTomato animals:
<a href="https://www.youtube.com/watch?v=gpVVqQLCe8Y">YouTube video</a>,
<a href="/X/Data/CRH-Cre/2p%20fluo4%20imaging%20in%20tdTomato%20neurons/">data folder</a>, and
<a href="http://192.168.1.9/X/Data%20Analysis/GCaMP6f%20PFC%20OXT%20response/onenote_notes.pdf">notes</a>.</li>
<li><a href="files/internal_k2.png">EPSCs and IPSCs are divergent at -70mV</a> using Scott's &quot;K2&quot; internal solution.</li>
<li><a href="/files/scope_frazier_vs_foster.png">comparison of slice optics between two similar microscopes</a></li>
<li><a href="https://youtu.be/4z3JDsVqICE">time series calcium imaging analysis video tutorial</a> (for GCaMP or Fluo-4 AM experiments)</li>
<li>GCaMP6f field imaging videos:
<a href="https://www.youtube.com/watch?v=1OHvPi1TbII">GABA-Cre PFC +GLU</a>,
<a href="https://www.youtube.com/watch?v=EEuXCMoRtsw">GABA-Cre mPFC +TGOT</a>,
<a href="https://www.youtube.com/watch?v=zYcEWnD3GCs">GABA-Cre iPFC +TGOT</a>,
<a href="https://youtu.be/tXZq13Gtk1I">OTR-Cre PFC +TGOT</a></li>
<li>Fiber photometry video
<a href="https://www.youtube.com/watch?v=r5iyD7B55EE">OTR-Cre PFC +GLU</a> and
<a href="https://github.com/swharden/ROI-Analysis-Pipeline/tree/master/pyFiber">software</a></li>
<li>Two-photon whole-cell experiment:
<a href="http://192.168.1.9/X/Data%20Analysis/_Tech%20Development/2p%20technique%20development/calcium%20dynamics%20with%20EGTA%20vs%20non/result_egta.png">EGTA vs EGTA-Free internal</a>,
<a href="http://192.168.1.9/X/Data%20Analysis/_Tech%20Development/2p%20technique%20development/calcium%20dynamics%20with%20EGTA%20vs%20non/result_protocol.png">back-acting AP protocol</a></li>
<li>Demonstration of <a href="/files/eyfp-ihc.jpg">immuno-amplification of eYFP in an OTR reporter</a> (IHC reveals axons not present at rig time)</li>
<li><a href="stock.php">Stock solution and aliquot calculator</a></li>
<li><a href="https://resources.rndsystems.com/images/site/rnd-systems-ihc-protocol-br.pdf">making formalin</a> (page 18)</li>
<li><a href="https://youtu.be/XsaoTr2YprI">multi-channel montage assembly with Fiji (ImageJ) and TrackEM2</a> (video)</li>
<li>Two-way ANOVA analysis of AP gain and IV curves <a href="https://youtu.be/u_i2kMZURew">video demonstration</a> with OriginLab and Prism 7</li>
<li>View a list of <a href="/files/activeFolders/results.csv.html">active folders</a> (organized by date) for the history of the lab.</li>
<li>Github <a href="https://github.com/swharden/SWHLab">projects by swharden</a></li>
<li>Display this server's <a href="phpinfo.php">PHP information</a></li>
<li>cjfraz.ddns.net:7109 (old lab wiki) <a href="http://cjfraz.ddns.net:7109/FrazierLab/PrivateWiki/index.php?title=Main_Page">link</a> (<code>23.123.105.215 cjfraz.ddns.net cjfraz.synology.me</code> / rattus)</li>
<li><a href="https://github.com/swharden/phpABF">phpABF</a> served locally: <a href="http://192.168.1.9/X/Lab%20Documents/network/repos/phpABF/">link</a></li>
</ul>
<h1>Equipment and Training</h1>
<ul>
<li>Adding scale bars in ImageJ: <a href="https://github.com/swharden/Microscopy/blob/master/microscope-scale-calibration/readme.md">link</a> and <a href="http://192.168.1.9/X/Lab%20Documents/scalebars.PNG">screenshot</a></li>
<li><a href="http://192.168.1.9/X/Users_Public/Scott/protocols/guide%20to%20patch%20clamp%20electrophysiology/source/patch-clamp-guide.pdf">Guide to Patch-Clamp Electrophysiology</a> (includes chapter on how to align DIC optics)</li>
</ul>
<h1>Authors</h1>
<ul>
<li>Charles J Frazier - <a href="https://orcid.org/0000-0003-3550-4789">ORCID</a></li>
<li>Scott W Harden - <a href="https://orcid.org/0000-0002-0757-1979">ORCID</a>, <a href="https://scholar.google.com/citations?user=egCaj-AAAAAJ">Google Scholar</a></li>
</ul>
<h1>CJFLab</h1>
<ul>
<li><a href="https://github.com/cjfraz/CJFLab/">CJFLab on GitHub</a></li>
<li>List of <a href="https://github.com/cjfraz/CJFLab/blob/master/documentation/commands.md">CJFLab commands</a></li>
</ul>
<h1>ACSF and Internal Solutions</h1>
<ul>
<li><a href="http://192.168.1.9/X/Users_Public/Scott/protocols/ACSF%20and%20internal%20solutions/internal-instructions.pdf">how to make internal solutions</a></li>
<li>internal solution recipes: <a href="http://192.168.1.9/X/Users_Public/Scott/protocols/ACSF%20and%20internal%20solutions/internal-kglu.pdf">k-glu</a>, <a href="http://192.168.1.9/X/Users_Public/Scott/protocols/ACSF%20and%20internal%20solutions/internal-CsMeSo3.pdf">CsMeSo3</a>, <a href="http://192.168.1.9/X/Users_Public/Scott/protocols/ACSF%20and%20internal%20solutions/internal-CsMeSo3-highCl.pdf">CsMeSo3 (high Cl)</a></li>
<li>ACSF recipes: <a href="http://192.168.1.9/X/Users_Public/Scott/protocols/ACSF%20and%20internal%20solutions/bath-solutions.pdf">Instructions for making 10x ACSF, Mg-Free ACSF, Dissecting Solution, and Sucrose Solution</a></li>
</ul><div align='right' style='font-size: 80%; color: #CCC; padding-right: 10px;'><a href='edit/?mdFileName=misc.md'>EDIT THIS PAGE</a></div></div>

<a name='browseABF'></a>
<div class="section">
    <h1>ABF Browser</h1>
    <div>Launch the given folder in the ABF browser website:</div>
    <form action="/SWHLabPHP/recode/src/">
        <input type="hidden" name="view" value="abf">
        <input type="hidden" name="frames">
        <input type="text" name="fldr" value="X:\Data\OTR-Cre\PFC inj eYFP OXT response\abfs" style="width:80%; font-family: monospace;">
        <input type="submit" value="launch">
    </form>
</div>

<a name='browseFolder'></a>
<div class="section">
    <h1>Folder-to-URL</h1>
    <div>Input an X-Drive path and a URL will be generated for it:</div>    
    <input type="text" name="fldr" id="pathForUrlConv" value="X:\Data\OTR-Cre\PFC inj eYFP OXT response\abfs" style="width:80%; font-family: monospace;" onkeypress="updatePath()">
    <div><br>That X-Drive path is available as a URL:<br><a href='' id='urlFromPath'>?</a></code></div>
    <br>
</div>

<a name='fileLocator'></a>
<div class="section">
    <h1>ABF Locator</h1>
    <div>Input the filename (not the full path) of an ABF and it will be located on the X-drive:</div>
    <iframe src="/SWHLabPHP/src/browse/findABF.php?view=iframe" style='height: 500;'></iframe>
</div>

<div class="section">
    <h1>File or Path Locator</h1>
    <iframe src="/404.php?view=iframe" style='height: 500;'></iframe>
</div>




<a name='edit'></a>
<div class="section">
    <h1>Editing this Page</h1>
    <div>Sections can be edited (with Notepad++) by editing the file listed on the bottom-right of each section.</div>    
    <div>Larger changes to this webpage can be made (with Notepad++ or Visual Studio Code) by editing:</div>    
	<div><code>X:\Lab Documents\network\htdocs\SWHLabPHP\src\browse\splash.php</code></div>
	<div><code>X:\Lab Documents\network\htdocs\SWHLabPHP\recode\src\functions\abf.php</code></div>
	<div><i>... but edit with caution, as one typo can break the lab website for everybody!</i></div>
    <br>
</div>



</div>

<div class='bannerBottom' style='height: 400px;'>

</div>

</body>
</html>
"""
links = [x.split(">")[0] for x in s.split("<a ")]
links = [x.replace("'", '"') for x in links]
links = [x.split('"') for x in links]
links = [x[1] for x in links if len(x)==3]
links = [x.split("fldr=")[1] for x in links if "fldr=" in x]
links = [x.split(";")[0] for x in links if ";" in x]
links = [x.split("&")[0] for x in links if "&" in x]
links = [x.replace("%20", " ") for x in links]
print("\n".join(links))
